USE [master]
GO

/****** Object:  Database [PadukaBajar]    Script Date: 11/09/2016 19:03:45 ******/
CREATE DATABASE [PadukaBajar] ON  PRIMARY 
( NAME = N'PadukaBajar', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\PadukaBajar.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PadukaBajar_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\PadukaBajar_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PadukaBajar] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PadukaBajar].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PadukaBajar] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PadukaBajar] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PadukaBajar] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PadukaBajar] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PadukaBajar] SET ARITHABORT OFF 
GO

ALTER DATABASE [PadukaBajar] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PadukaBajar] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [PadukaBajar] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PadukaBajar] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PadukaBajar] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PadukaBajar] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PadukaBajar] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PadukaBajar] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PadukaBajar] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PadukaBajar] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PadukaBajar] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PadukaBajar] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PadukaBajar] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PadukaBajar] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PadukaBajar] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PadukaBajar] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PadukaBajar] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PadukaBajar] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PadukaBajar] SET  READ_WRITE 
GO

ALTER DATABASE [PadukaBajar] SET RECOVERY FULL 
GO

ALTER DATABASE [PadukaBajar] SET  MULTI_USER 
GO

ALTER DATABASE [PadukaBajar] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PadukaBajar] SET DB_CHAINING OFF 
GO

