USE [master]
GO

/****** Object:  Database [PadukaBazarDB]    Script Date: 11/09/2016 19:00:53 ******/
CREATE DATABASE [PadukaBazarDB] ON  PRIMARY 
( NAME = N'PadukaBazarDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\PadukaBazarDB.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PadukaBazarDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\PadukaBazarDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PadukaBazarDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PadukaBazarDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PadukaBazarDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PadukaBazarDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PadukaBazarDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PadukaBazarDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PadukaBazarDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [PadukaBazarDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PadukaBazarDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [PadukaBazarDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PadukaBazarDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PadukaBazarDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PadukaBazarDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PadukaBazarDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PadukaBazarDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PadukaBazarDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PadukaBazarDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PadukaBazarDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PadukaBazarDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PadukaBazarDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PadukaBazarDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PadukaBazarDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PadukaBazarDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PadukaBazarDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PadukaBazarDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PadukaBazarDB] SET  READ_WRITE 
GO

ALTER DATABASE [PadukaBazarDB] SET RECOVERY FULL 
GO

ALTER DATABASE [PadukaBazarDB] SET  MULTI_USER 
GO

ALTER DATABASE [PadukaBazarDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PadukaBazarDB] SET DB_CHAINING OFF 
GO

